Editor summernote
luisza/django-gentelella-widgets pull request #29
Opened 2020-11-24 06:12 UTC by Kejebo

Add summernote editor to gentelella
![wysiwyg](https://user-images.githubusercontent.com/57534905/100055594-a7285400-2de9-11eb-95a1-9c9872c208be.png)

2020-11-24 23:17 UTC, luisza commented on djgentelella/static/gentelella/js/base.js
> +function uploadFile(url_pages,file, editor) {
Este código no va acá, si no en wysiwyg.js

2020-11-24 23:38 UTC, luisza requested changes
Debe modifcar las observaciones para poder incorporar los cambios.

2020-11-24 23:38 UTC, luisza commented on djgentelella/templates/gentelella/base.html
>  {% load  gentelellamenu gtsettings %}
Algo pasa con este archivo ya que tiene mucho cambios de forma que hace muy dificil saber que fue lo que se cambió

2020-11-24 23:38 UTC, luisza commented on djgentelella/templates/gentelella/widgets/wysiwyg.html
> +<textarea style="overflow:scroll; max-height:300px" data-url="{% url 'upload_image'%}" name="{{ widget.name }}"{% include "gentelella/widgets/attrs.html" %}>
Sería conveniente que la parte de style="..." sea una clase y no quemado en el html

2020-11-24 23:54 UTC, Kejebo commented on djgentelella/static/gentelella/js/base.js
> +function uploadFile(url_pages,file, editor) {
Se genero cuando realice el createbasejs al parecer esa clase incorporo el codigo en el base.js

2020-12-02 02:40 UTC, luisza commented
Merge with changes on development

2020-12-02 02:40 UTC, closed without merging